openapi: 3.0.0
info:
  title: deliveryboy
  version: '1.0'
  contact:
    name: RATrustvox
    email: ti.trustvox@reclameaqui.com.br
  description: Deliveryboy internal API
servers:
  - url: 'http://localhost:3000'
paths:
  /scheduling:
    post:
      summary: Schedule
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scheduling'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
      operationId: create-scheduling
      description: Issues an scheduling request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                scheduling:
                  type: object
                  required:
                    - recipient
                    - channel
                    - campaign
                    - scheduled_to
                  properties:
                    recipient:
                      type: string
                      description: "Receiver's email or phone number"
                    channel:
                      type: string
                      description: Channel to be used in order to reach the receiver
                      enum:
                        - email
                        - sms
                    priority:
                      type: string
                      default: low
                      enum:
                        - low
                        - middle
                        - high
                      description: Priority queue in which it should be processed
                    scheduled_to:
                      type: string
                      description: Date and time where the message should be delivered
                      format: time
                    campaign:
                      type: string
                      description: Responsys campaign name
                    payload:
                      type: object
                      description: Any tuple of customization tag and its value
              required:
                - scheduling
        description: Scheduling params
      parameters: []
      tags:
        - endpoints
components:
  schemas:
    Scheduling:
      type: object
      description: Stores scheduling information to later delivery
      properties:
        data:
          type: object
          required:
            - recipient
            - channel
            - priority
            - status
            - scheduled_to
            - campaign
            - created_at
          properties:
            recipient:
              type: string
            channel:
              type: string
              enum:
                - email
                - sms
            priority:
              type: string
              enum:
                - low
                - middle
                - high
            status:
              type: string
              enum:
                - created
                - scheduled
                - delivered
                - failed
            scheduled_to:
              type: string
              format: time
            campaign:
              type: string
            created_at:
              type: string
              format: time
      required:
        - data
      x-tags:
        - schemas
